Fix for messages retaining components, files and allowedMentions options
skyra-project/editable-commands pull request #144
Opened 2022-07-09 16:03 UTC by KrishAgarwal2811

This PR fixes the issues when makes the edited messages still retain the old components, files and allowedMentions options if any.

2022-07-09 20:05 UTC, kyranet requested changes

2022-07-09 20:05 UTC, kyranet commented on src/index.ts
> +			: { content: null, embeds: [], attachments: [], components: [], files: [], allowedMentions: undefined, ...options };
`files` and `allowedMentions` are not necessary here, they don't spread across updates.

2022-07-10 10:14 UTC, kyranet approved these changes

2022-07-10 10:14 UTC, merged

2022-07-19 15:48 UTC, favna commented
@all-contributors please add @KrishAgarwal2811 for code